import bar from './bar.jpg';
import bbc_logo from './bbc_logo.png';
import budweiser from './budweiser_logo.svg';
import cartaIcon from './carta.svg';
import clubColombia from './club_colombia.svg';
import clubColombia_logo from './club_colombia_logo.png';
import clubes from './clubes.jpg';
import corona from './corona.svg';
import corona_logo from './corona_logo.svg';
import discoteca from './discoteca.jpg';
import facebook_icon from './facebook_icon.svg';
import instagram_icon from './instagram_icon.svg';
import logoHighEnd from './logo_high_end.svg';
import logoHighEndCali from './logo_high_end_cali.png';
import mapaIcon from './mapa.svg';
import reservaIcon from './reserva.svg';
import restaurante from './restaurante.jpg';
import rooftop from './rooftop.jpg';
import stella from './stella.svg';
import stella_logo from './stella_logo.svg';
import x_icon from './x_icon.svg';

export const assetsBarranquilla = {
    bar,
    bbc_logo,
    budweiser,
    cartaIcon,
    clubColombia_logo,
    clubColombia,
    clubes,
    corona_logo,
    corona,
    discoteca,
    facebook_icon,
    instagram_icon,
    logoHighEnd,
    logoHighEndCali,
    mapaIcon,
    reservaIcon,
    restaurante,
    rooftop,
    stella_logo,
    stella,
    x_icon,
};

export const sites_list_barranquilla = [
    {
        site_name: "Restaurante",
        site_image: restaurante
    },
    {
        site_name: "Bar",
        site_image: bar
    },
    {
        site_name: "Sportbar",
        site_image: discoteca
    },
    {
        site_name: "Plaza Turística",
        site_image: discoteca
    },
    {
        site_name: "Beach Club",
        site_image: discoteca
    },
]

export const location_list_barranquilla = [
    {
        _id: "1",
        address: "Cra. 55 #75 - 67",
        carta: "",
        category: "Restaurante",
        description: "",
        dress_code: "",
        image_carousel: [],
        image: logoHighEnd,
        lat: 11.002929,
        lng: -74.8059268,
        marca_logo: stella_logo,
        marca: stella,
        marker: null,
        name: "Okra",
        promo: "",
        schedule: "12pm-11pm",
        subtitle: "Restaurante",
        url_reserva: ""
    },
    {
        _id: "2",
        address: "Cra. 55 #75 - 67",
        carta: "",
        category: "Restaurante",
        description: "",
        dress_code: "",
        image_carousel: [],
        image: logoHighEnd,
        lat: 11.002929,
        lng: -74.8059268,
        marca_logo: clubColombia_logo,
        marca: clubColombia,
        marker: null,
        name: "Palo de Mango",
        promo: "",
        schedule: "12pm-3pm. 5pm-11pm",
        subtitle: "Restaurante",
        url_reserva: ""
    },
    {
        _id: "3",
        address: "Cra. 55 #75 - 67",
        carta: "",
        category: "Restaurante",
        description: "",
        dress_code: "",
        image_carousel: [],
        image: logoHighEnd,
        lat: 11.002929,
        lng: -74.8059268,
        marca_logo: stella_logo,
        marca: stella,
        marker: null,
        name: "Lola Bar",
        promo: "",
        schedule: "12pm-3pm. 5pm-11pm",
        subtitle: "Restaurante",
        url_reserva: ""
    },
    {
        _id: "4",
        address: "Cra. 55 #75 - 67",
        carta: "",
        category: "Restaurante",
        description: "",
        dress_code: "",
        image_carousel: [],
        image: logoHighEnd,
        lat: 11.002929,
        lng: -74.8059268,
        marca_logo: stella_logo,
        marca: stella,
        marker: null,
        name: "Kinto Elemento",
        promo: "",
        schedule: "12pm-3pm. 6pm-11pm",
        subtitle: "Restaurante",
        url_reserva: ""
    },
    {
        _id: "5",
        address: "Cra. 52 #76 - 208",
        carta: "",
        category: "Restaurante",
        description: "",
        dress_code: "",
        image_carousel: [],
        image: logoHighEnd,
        lat: 11.0033764,
        lng: -74.8128998,
        marca_logo: stella_logo,
        marca: stella,
        marker: null,
        name: "Noa Sushi & Robata",
        promo: "",
        schedule: "12pm-3pm. 6pm-11pm",
        subtitle: "Restaurante",
        url_reserva: ""
    },
    {
        _id: "6",
        address: "Cra. 51B #79-211",
        carta: "",
        category: "Restaurante",
        description: "",
        dress_code: "",
        image_carousel: [],
        image: logoHighEnd,
        lat: 11.0031797,
        lng: -74.8159527,
        marca_logo: stella_logo,
        marca: stella,
        marker: null,
        name: "La Única",
        promo: "",
        schedule: "12pm-4pm. 7pm-12pm",
        subtitle: "Restaurante",
        url_reserva: ""
    },
    {
        _id: "7",
        address: "Cl. 98 #56-18",
        carta: "",
        category: "Restaurante",
        description: "",
        dress_code: "",
        image_carousel: [],
        image: logoHighEnd,
        lat: 11.0158101,
        lng: -74.8257723,
        marca_logo: corona_logo,
        marca: corona,
        marker: null,
        name: "Tripulante",
        promo: "",
        schedule: "12pm-4pm. 7pm-12pm",
        subtitle: "Restaurante",
        url_reserva: ""
    },
    {
        _id: "8",
        address: "Cl. 85 #50-159",
        carta: "",
        category: "Bar",
        description: "",
        dress_code: "",
        image_carousel: [],
        image: logoHighEnd,
        lat: 11.0064954,
        lng: -74.8219655,
        marca_logo: budweiser,
        marca: budweiser,
        marker: null,
        name: "JRr Boutique de Licores",
        promo: "",
        schedule: "10am-4am",
        subtitle: "Bar",
        url_reserva: ""
    },
    {
        _id: "9",
        address: "Cl. 84 #59-34",
        carta: "",
        category: "Sportbar",
        description: "",
        dress_code: "",
        image_carousel: [],
        image: logoHighEnd,
        lat: 11.0105891,
        lng: -74.8142204,
        marca_logo: budweiser,
        marca: budweiser,
        marker: null,
        name: "Coliseo Sport Bar 84",
        promo: "",
        schedule: "12pm-11pm",
        subtitle: "Sportbar",
        url_reserva: ""
    },
    {
        _id: "10",
        address: "Cl. 99 #53 - 40",
        carta: "",
        category: "Sportbar",
        description: "",
        dress_code: "",
        image_carousel: [],
        image: logoHighEnd,
        lat: 11.0158471,
        lng: -74.8279911,
        marca_logo: budweiser,
        marca: budweiser,
        marker: null,
        name: "Zamba Salsa Sport Bar",
        promo: "",
        schedule: "4pm-4am",
        subtitle: "Sportbar",
        url_reserva: ""
    },
    {
        _id: "11",
        address: "Cra. 53 #75-124",
        carta: "",
        category: "Bar",
        description: "",
        dress_code: "",
        image_carousel: [],
        image: logoHighEnd,
        lat: 11.0023253,
        lng: -74.8077317,
        marca_logo: clubColombia_logo,
        marca: clubColombia,
        marker: null,
        name: "La Popular",
        promo: "",
        schedule: "6pm-3am",
        subtitle: "Bar",
        url_reserva: ""
    },
    {
        _id: "12",
        address: "Cl. 1 #57 5, Puerto Colombia",
        carta: "",
        category: "Plaza Turística",
        description: "",
        dress_code: "",
        image_carousel: [],
        image: logoHighEnd,
        lat: 10.9896634,
        lng: -74.9614565,
        marca_logo: clubColombia_logo,
        marca: clubColombia,
        marker: null,
        name: "Centro Gastronómico Internacional Muelle 1888",
        promo: "",
        schedule: "12pm-10pm",
        subtitle: "Plaza Turística",
        url_reserva: ""
    },
    {
        _id: "13",
        address: "Cra. 51B # 79 - 97",
        carta: "",
        category: "Restaurante",
        description: "",
        dress_code: "",
        image_carousel: [],
        image: logoHighEnd,
        lat: 11.0027086,
        lng: -74.810051,
        marca_logo: clubColombia_logo,
        marca: clubColombia,
        marker: null,
        name: "Varadero",
        promo: "",
        schedule: "12am-11pm",
        subtitle: "Restaurante",
        url_reserva: ""
    },
    {
        _id: "14",
        address: "Cra. 53 #85 13",
        carta: "",
        category: "Restaurante",
        description: "",
        dress_code: "",
        image_carousel: [],
        image: logoHighEnd,
        lat: 11.0078999,
        lng: -74.820032,
        marca_logo: clubColombia_logo,
        marca: clubColombia,
        marker: null,
        name: "CUCAYO - Cocina de Aquí",
        promo: "",
        schedule: "8am-11pm",
        subtitle: "Restaurante",
        url_reserva: ""
    },
    {
        _id: "15",
        address: "Cra. 52 #76-126",
        carta: "",
        category: "Restaurante",
        description: "",
        dress_code: "",
        image_carousel: [],
        image: logoHighEnd,
        lat: 11.0031265,
        lng: -74.809902,
        marca_logo: stella_logo,
        marca: stella,
        marker: null,
        name: "Mistura",
        promo: "",
        schedule: "12pm-3pm. 7pm-11pm",
        subtitle: "Restaurante",
        url_reserva: ""
    },
    {
        _id: "16",
        address: "Cra. 52 #76 - 208",
        carta: "",
        category: "Bar",
        description: "",
        dress_code: "",
        image_carousel: [],
        image: logoHighEnd,
        lat: 11.003365,
        lng: -74.8084014,
        marca_logo: stella_logo,
        marca: stella,
        marker: null,
        name: "Barlao",
        promo: "",
        schedule: "6pm-1am",
        subtitle: "Bar",
        url_reserva: ""
    },
    {
        _id: "17",
        address: "Cl. 2 #22-61, Puerto Colombia",
        carta: "",
        category: "Beach Club",
        description: "",
        dress_code: "",
        image_carousel: [],
        image: logoHighEnd,
        lat: 11.0058973,
        lng: -74.9548221,
        marca_logo: corona_logo,
        marca: corona,
        marker: null,
        name: "Hotel Pradomar",
        promo: "",
        schedule: "9am-9pm",
        subtitle: "Beach Club",
        url_reserva: ""
    },
    {
        _id: "18",
        address: "Cra. 59b #81- 158",
        carta: "",
        category: "Restaurante",
        description: "",
        dress_code: "",
        image_carousel: [],
        image: logoHighEnd,
        lat: 11.0110896,
        lng: -74.8096925,
        marca_logo: stella_logo,
        marca: stella,
        marker: null,
        name: "Segundo",
        promo: "",
        schedule: "6pm-12am",
        subtitle: "Restaurante",
        url_reserva: ""
    },
    {
        _id: "19",
        address: "Cra. 59b #81- 158",
        carta: "",
        category: "Restaurante",
        description: "",
        dress_code: "",
        image_carousel: [],
        image: logoHighEnd,
        lat: 11.0110896,
        lng: -74.8096925,
        marca_logo: stella_logo,
        marca: stella,
        marker: null,
        name: "Devoto",
        promo: "",
        schedule: "10am-9pm",
        subtitle: "Restaurante",
        url_reserva: ""
    },
    {
        _id: "20",
        address: "Cl. 99 #53 - 40",
        carta: "",
        category: "Restaurante",
        description: "",
        dress_code: "",
        image_carousel: [],
        image: logoHighEnd,
        lat: 11.0110896,
        lng: -74.8096925,
        marca_logo: stella_logo,
        marca: stella,
        marker: null,
        name: "Redentor",
        promo: "",
        schedule: "12pm-10pm",
        subtitle: "Restaurante",
        url_reserva: ""
    },
    {
        _id: "21",
        address: "Cra. 52 #74-73",
        carta: "",
        category: "Bar",
        description: "",
        dress_code: "",
        image_carousel: [],
        image: logoHighEnd,
        lat: 11.0074484,
        lng: -74.8213871,
        marca_logo: bbc_logo,
        marca: bbc_logo,
        marker: null,
        name: "Bourbon St.",
        promo: "",
        schedule: "6pm-3am",
        subtitle: "Bar",
        url_reserva: ""
    },
    {
        _id: "22",
        address: "Cl. 84 #44-60",
        carta: "",
        category: "Bar",
        description: "",
        dress_code: "",
        image_carousel: [],
        image: logoHighEnd,
        lat: 11.0004514,
        lng: -74.8240651,
        marca_logo: budweiser,
        marca: budweiser,
        marker: null,
        name: "Logia Licores",
        promo: "",
        schedule: "4pm-4am",
        subtitle: "Bar",
        url_reserva: ""
    },
    {
        _id: "23",
        address: "Cl. 99 #53 - 40",
        carta: "",
        category: "Bar",
        description: "",
        dress_code: "",
        image_carousel: [],
        image: logoHighEnd,
        lat: 11.0152751,
        lng: -74.8290945,
        marca_logo: corona_logo,
        marca: corona,
        marker: null,
        name: "Cantina La María",
        promo: "",
        schedule: "6pm-3am",
        subtitle: "Bar",
        url_reserva: ""
    },
    {
        _id: "24",
        address: "Cra. 51B #85-16",
        carta: "",
        category: "Restaurante",
        description: "",
        dress_code: "",
        image_carousel: [],
        image: logoHighEnd,
        lat: 11.0069732,
        lng: -74.8191085,
        marca_logo: clubColombia_logo,
        marca: clubColombia,
        marker: null,
        name: "El Punto Múltiple del Sabor",
        promo: "",
        schedule: "11am-11pm",
        subtitle: "Restaurante",
        url_reserva: ""
    },
    {
        _id: "25",
        address: "Cra 53 #85-61",
        carta: "",
        category: "Restaurante",
        description: "",
        dress_code: "",
        image_carousel: [],
        image: logoHighEnd,
        lat: 11.0082417,
        lng: -74.8226603,
        marca_logo: stella_logo,
        marca: stella,
        marker: null,
        name: "Porthos Steakhouse and Pub 53",
        promo: "",
        schedule: "12pm-11pm",
        subtitle: "Restaurante",
        url_reserva: ""
    },








]
